### ISSUE TITLE
Won't work if two array keys have equal values

### ISSUE THREAD

**Issue by danaki** [sergiors/applyzer#2]
To reproduce:
```
$data = [
  "firstname" => "test",
  "lastname" => "test"
];

$user = new User();
$user = Applyzer::apply($data, $user);

echo($user->getFirstname());
echo($user->getLastname());
```

**Comment by sergiors** [comment]
😱  Could you fix it?

**Comment by danaki** [comment]
No, I decided not to use Applyzer in my project until YOU fix it 🤣

**Comment by sergiors** [comment]
Oh lord 😅 
Maybe at weekend I do that

**Comment by arojunior** [comment]
The **formalize** method is using **array_flip** and it removes the duplicate keys.

This code solves the problem:
```php
     private function formalize(array $data)
     {
         $newData = array();
         foreach($data as $key => $value) {
            $newData = array_merge(
                $newData, [$this->formatAttribute($key) => $value]
            );
         }
         return $newData;
     }
```

But then you have two things to think about:

1. It is not using a "functional way" like the rest of the lib.
2. The **formatAttribute** method now does not format the attribute, but the key.

**Comment by sergiors** [comment]
I think I can use `array_reduce` with to avoid `foreach`

**Comment by sergiors** [comment]
Thanks @arojunior for the help!
